server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

cors:
  allowed-origins: "http://localhost:3000"

spring:
  datasource:
    url: 'jdbc:postgresql://ep-odd-haze-aoe6yh87-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
    driver-class-name: 'org.postgresql.Driver'
    username: 'neondb_owner'
    password: 'npg_wQO0bVlTGZ5o'

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update # 처음 실행 시 create로 테이블을 만들고 싶다면 'create'로 변경하세요
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Gemini API 키
gemini:
  api:
    key: AIzaSyBwCnOkxMhkDxkTYJvhDhTv2Ld0U47_I7Y

# 로깅 설정
logging:
  level:
    root: info
    com.nuri.nuriai: debug